services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: node --watch server.js
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mini_social_db

volumes:
  mongodb:
